package com.ch12.dao.model;

import lombok.Data;

import java.util.Date;

@Data
public class Scheduler {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduler.scheduler_id
     *
     * @mbggenerated
     */
    private Integer schedulerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduler.job_name
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduler.job_groud
     *
     * @mbggenerated
     */
    private String jobGroud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduler.job_cron
     *
     * @mbggenerated
     */
    private String jobCron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduler.job_create
     *
     * @mbggenerated
     */
    private Date jobCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduler.scheduler_id
     *
     * @return the value of scheduler.scheduler_id
     *
     * @mbggenerated
     */
    public Integer getSchedulerId() {
        return schedulerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduler.scheduler_id
     *
     * @param schedulerId the value for scheduler.scheduler_id
     *
     * @mbggenerated
     */
    public void setSchedulerId(Integer schedulerId) {
        this.schedulerId = schedulerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduler.job_name
     *
     * @return the value of scheduler.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduler.job_name
     *
     * @param jobName the value for scheduler.job_name
     *
     * @mbggenerated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduler.job_groud
     *
     * @return the value of scheduler.job_groud
     *
     * @mbggenerated
     */
    public String getJobGroud() {
        return jobGroud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduler.job_groud
     *
     * @param jobGroud the value for scheduler.job_groud
     *
     * @mbggenerated
     */
    public void setJobGroud(String jobGroud) {
        this.jobGroud = jobGroud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduler.job_cron
     *
     * @return the value of scheduler.job_cron
     *
     * @mbggenerated
     */
    public String getJobCron() {
        return jobCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduler.job_cron
     *
     * @param jobCron the value for scheduler.job_cron
     *
     * @mbggenerated
     */
    public void setJobCron(String jobCron) {
        this.jobCron = jobCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduler.job_create
     *
     * @return the value of scheduler.job_create
     *
     * @mbggenerated
     */
    public Date getJobCreate() {
        return jobCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduler.job_create
     *
     * @param jobCreate the value for scheduler.job_create
     *
     * @mbggenerated
     */
    public void setJobCreate(Date jobCreate) {
        this.jobCreate = jobCreate;
    }
}