package com.cloud.frame.auth.user.dao.model;

public class AdminRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.rid
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.aid
     *
     * @return the value of admin_role.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.aid
     *
     * @param aid the value for admin_role.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.rid
     *
     * @return the value of admin_role.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.rid
     *
     * @param rid the value for admin_role.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}