package com.cloud.frame.security.oauth2.dao.mapper;

import com.cloud.frame.security.oauth2.dao.model.AdminRole;

import java.util.List;

public interface AdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int insert(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    List<AdminRole> selectAll();
}