package com.dao.mapper;

import com.dao.model.OsUser;
import java.util.List;

public interface OsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user
     *
     * @mbggenerated
     */
    int insert(OsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user
     *
     * @mbggenerated
     */
    OsUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user
     *
     * @mbggenerated
     */
    List<OsUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OsUser record);
}